#!/bin/bash
set -eou pipefail
export DISPLAY=:0.0
xrandr --output HDMI-1 --rotate left
xset -dpms
xset s off
xset s noblank
matchbox-window-manager -use_titlebar no -use_desktop_mode plain -use-cursor no &

cd /home/pi/mirror-v2

./wait github.com 443

git reset origin --hard
git pull

aws s3 cp --recursive s3://magic-mirror-v2/ ./dist
pnpm install --production

pnpm run serve &
pnpm run lite-ci &

./wait 127.0.0.1 3000
midori -e Fullscreen -a http://localhost:3000 