#!/bin/bash

cd /home/pi/mirror-v2

source .env

./wait github.com 443

git reset origin --hard
git pull

aws s3 cp --recursive s3://magic-mirror-v2/ ./dist
npm install --production

npm run serve &
npm run lite-ci &

./wait 127.0.0.1 3000

sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ../.config/chromium/Default/Preferences
sed -i 's/"exit_type": "Crashed"/"exit_type": "Normal"/' ../.config/chromium/Default/Preferences

chromium-browser --kiosk --allow-insecure-localhost --disable-session-crashed-bubble --disable-infobars 127.0.0.1:3000
