#!/bin/bash
set -euo pipefail

host="${1}"
port="${2:-443}"
printf "%s" "waiting for $host:$port"
while ! nc -vz "${host}" "${port}" &> /dev/null && sleep 1
do
    printf "%c" "."
done
printf "\n%s\n"  "$host:$port is online"