name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: check types
        run: npm run check-ts

      - name: check prettier
        run: npm run prettier-check

      - name: make sure build works
        run: npm run build
