name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install pnpm
        run: npm i -g pnpm@8 --force

      - name: install packages
        run: pnpm install

      - name: check types
        run: pnpm run check-ts

      - name: check prettier
        run: pnpm run prettier-check

      - name: make sure build works
        run: pnpm run build
