name: Publish
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: check types
        run: npm run publish
