name: Publish
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: check types
        run: npm run check-ts

      - name: build
        run: npm run build --production

      - name: publish
        run: |
          cd dist
          aws s3 cp --recursive --acl public-read . s3://magic-mirror-v2
